class AppStrings {
  AppStrings._();

  static const String appName = 'Hiring App';
  static const String home = 'Home';
  static const String onboarding = 'Onboarding';
  static const String getSetHired = 'Get Set Hired!';
  static const String hiringMadeEasy = 'Hiring Made Easy';
  static const String registerToContinue = 'Register to continue';
  static const String alreadyHaveAccount = 'Already have an account?';
  static const String login = 'Login';
  static const String welcomeToApp = 'Welcome to Hiring App!';
  static const String pleaseLogin = 'Please Login to continue.';
  static const String pleaseRegister = 'Please create an account to continue.';
  static const String dontHaveAccount = 'Don\'t have a account?';
  static const String register = 'Register';
  static const String forgotPassword = 'Forgot Password?';
  static const String provideYourEmail = 'Provide your email';
  static const String youWillGetLink =
      'You will get a link to reset your account password.';
  static const String agreeTermsAndConditions =
      'By signing in, you agree to our terms and conditions.';
  static const String role = 'Role';
  static const String email = 'Email';
  static const String password = 'Password';
  static const String confirmPassword = 'Confirm Password';
  static const String enterPassword = 'Enter Password';
  static const String emailExample = 'example@company.domain';
  static const String submit = 'Submit';
  static const String goBack = 'Go Back';
  static const String logout = 'Logout';
  static const String deleteAccount = 'Delete Account';
  static const String candidate = 'Candidate';
  static const String recruiter = 'Recruiter';
  static const String yes = 'Yes';
  static const String no = 'No';
  static const String passwordSent =
      'Password has been sent to you.\nPlease check your email!';
  static const String cantNull = 'This field can\'t be empty.';
  static const String sureToLogout = 'Are you sure to logout?';
  static const String sureToDelete = 'Are you sure to delete account?';
  static const String actionIrreversible = 'This action is irreversible!';
  static const String completeProfile = 'Complete your profile to get started!';
  static const String male = 'Male';
  static const String female = 'Female';
  static const String gender = 'Gender';
  static const String name = 'Name';
  static const String companyName = 'Company Name';
  static const String employees = 'Employees';
  static const String city = 'City';
  static const String dob = 'Date of Birth';
  static const String dobExample = 'DD/MM/YYYY';
  static const String fresher = 'Fresher';
  static const String experienced = 'Experienced';
  static const String iAm = 'I Am';
  static const String nameExample = 'John Doe';
  static const String companyNameExample = 'XYZ Pvt. Ltd.';
  static const String candidateProfile = 'Candidate Profile';
  static const String recruiterProfile = 'Recruiter Profile';
  static const String sector = 'Sector';
  static const String government = 'Government';
  static const String semiGovernment = 'Semi-Government';
  static const String private = 'Private';
  static const String companySize = 'Company Size';
  static const String website = 'Website';
  static const String websiteExample = 'www.example.com';
  static const String phoneExample = '9876543210';
  static const String phone = 'Phone';
  static const String jobTitle = 'Job Title';
  static const String jobTitleExample = 'Flutter Developer';
  static const String fullTime = 'Full Time';
  static const String partTime = 'Part Time';
  static const String contract = 'Contract';
  static const String internship = 'Internship';
  static const String jobType = 'Job Type';
  static const String onSite = 'On-site';
  static const String remote = 'Remote';
  static const String hybrid = 'Hybrid';
  static const String jobCulture = 'Job Culture';
  static const String jobDescription = 'Job Description';
  static const String jobDescriptionExample =
      'We are looking for flutter developer...';
  static const String location = 'Location';
  static const String payRange = 'Pay Range';
  static const String apply = 'Apply';

  static const String jobs = 'Jobs';
  static const String profile = 'Profile';
  static const String hoursAgo = 'hours ago';
  static const String welcomeBack = 'Welcome Back';
  static const String addNewJobs = 'Add new jobs from below (+)';
  static const String addNewJob = 'Add New Job';
  static const String jobAdded = 'Job Added Successfully';
}
